server:
  port: ${PORT:8080}

spring:
  application:
    name: charger-manager
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/charger_db}
    username: ${DB_USER:charger}
    password: ${DB_PASSWORD:charger}
    driver-class-name: org.postgresql.Driver
  mail:
    host: ${MAIL_HOST:sandbox.smtp.mailtrap.io}
    port: ${MAIL_PORT:587}
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        debug: ${MAIL_DEBUG:true}
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000
  notifications:
    email:
      from: ${MAIL_FROM:no-reply@charger-manager.com}
      subject-prefix: ${MAIL_SUBJECT_PREFIX:[Charger Manager] }

charger-proxy:
  soap:
    charge-url: ${CHARGER_PROXY_CHARGE_URL:http://localhost:8082/ws/charge}
    customer-url: ${CHARGER_PROXY_CUSTOMER_URL:http://localhost:8082/ws/customer}
