server:
    port: ${PORT}

spring:
    application:
        name: charger-proxy
    datasource:
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        driver-class-name: org.postgresql.Driver

# Configurações do ASAAS
asaas:
    api:
        key: ${ASAAS_API_KEY}
    env: ${ASSAS_ENV:SANDBOX}
